### ISSUE TITLE
File "/usr/lib64/python2.7/ConfigParser.py", line 370, in getboolean

### ISSUE THREAD

**Issue by bertalanimre** [splitbrain/Watcher#22]
# System

- CentOS 7.1
- Package python-2.7.5-58.el7.x86_64 installed 
- Package python-inotify-0.9.4-4.el7.noarch installed

## What did I miss during installation?

```
2017-10-17 11:09:31.756856 Daemon started
2017-10-17 11:09:31.757472 web:nginx: /var/www/html
Traceback (most recent call last):
  File "/bin/watcher", line 384, in <module>
    daemon.start()
  File "/bin/watcher", line 124, in start
    self.run()
  File "/bin/watcher", line 271, in run
    recursive = self.config.getboolean(section,'recursive')
  File "/usr/lib64/python2.7/ConfigParser.py", line 370, in getboolean
    raise ValueError, 'Not a boolean: %s' % v
ValueError: Not a boolean:
```

**Comment by bertalanimre** [comment]
It was a syntax error in the ini file. Stupid me....
